language: node_js
node_js:
- 10

env:
  global:
    - GIT_NAME: Travis CI
    - GIT_EMAIL: zerodividedby0@gmail.com
    - GITHUB_REPO: zeroby0/Basic-Electronics
    - GIT_SOURCE: _docpress

script:
- npm install docpress && ./node_modules/.bin/docpress build

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm install git-update-ghpages && ./node_modules/.bin/git-update-ghpages -e; fi


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _docpress
  on:
    branch: gh-pages